### ISSUE TITLE
Issue Contribution Guidelines

### ISSUE THREAD

**Issue by WickedTree** [Trivia-Bot-Discord/trivia-bot#69]
Please read this before filing any issues
<hr />

# What are issues and how do we use them
We use issues to track bugs in Trivia bot, and to track feature requests. Any questions about how to use the bot or help with specific issues should be done in our [discord support server.](discord.gg/UHQ33Qe)
# How long will it take to resolve a reported bug?
We usually will reply and/or fix the bug within 5 days, but we do not guarantee it. If your issue is innapropriate or should have been asked in the discord support server, we will close it and ask you to ask it in the support server. If you repeatedly do this, we may flag your issues as spam and block you from interacting with this repository.
# How long will it take to add a new feature?
This may take up to months depending on what the feature is, and if we believe that it should be added. Please see our [project board](https://github.com/orgs/Trivia-Bot-Discord/projects/1) to see our progress on any bugs or issues

<hr />

Thank you for following these guidelines, and we hope you enjoy using our bot!

**Comment by gubareve** [comment]
ytho
